# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/
    - test-kitura

# the matrix of builds should cover each combination of Swift version
# and platform that is supported. The version of Swift used is specified
# by .swift-version, unless SWIFT_SNAPSHOT is specified.
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3 CUSTOM_TEST_SCRIPT=.kitura-test.sh
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.3 CUSTOM_TEST_SCRIPT=.kitura-test.sh
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_TEST_ARGS="--parallel"
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 DOCKER_PRIVILEGED=true
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT DOCKER_PRIVILEGED=true
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:18.04 DOCKER_PRIVILEGED=true
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3 BREW_INSTALL_PACKAGES="libressl" CUSTOM_TEST_SCRIPT=.kitura-test.sh
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.2 JAZZY_ELIGIBLE=true CODECOV_ELIGIBLE=true BREW_INSTALL_PACKAGES="libressl"
    - os: osx
      osx_image: xcode10
      sudo: required
      env: SWIFT_TEST_ARGS="--parallel" BREW_INSTALL_PACKAGES="libressl"
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT BREW_INSTALL_PACKAGES="libressl" CUSTOM_TEST_SCRIPT=.kitura-test.sh

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

before_script:
  - export -f travis_nanoseconds
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
